spring:
  application:
    name: songforyou

  datasource:
    url:
      jdbc:postgresql://songforyou.postgres.database.azure.com:5432/songforyou
    username: laweeaqprv
    password: gRO0R736et0sURF$
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 80