name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.PRIVATE_TOKEN }}
      - name: Update submodules
        run: |
          git pull --recurse-submodules
          git submodule update --init --recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Deploy to Azure VM
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'songforyou'
          publish-profile: ${{ secrets.AZURE_VM_PUBLISH_PROFILE }}
          package: '*.jar'
